"""
Generate exportable reports from analysis results.
"""

from typing import List, Dict
import csv
from io import StringIO
from datetime import datetime


class ExportGenerator:
    """Generate various export formats from analysis data"""

    @staticmethod
    def generate_csv(analysis_result: Dict) -> str:
        """
        Generate CSV report from analysis results.
        Returns CSV as string.
        """
        output = StringIO()
        writer = csv.writer(output)

        # Header
        writer.writerow([
            "Deal Name",
            "Issue Category",
            "Severity",
            "Rule Name",
            "Issue Description",
            "Remediation Action",
            "Remediation Owner",
            "Field Affected",
            "Current Value"
        ])

        # Get violations
        violations_by_deal = analysis_result.get("violations_by_deal", {})

        # Write each violation as a row
        for deal_name, violations in violations_by_deal.items():
            for violation in violations:
                writer.writerow([
                    deal_name,
                    violation.get("category", ""),
                    violation.get("severity", "").upper(),
                    violation.get("rule_name", ""),
                    violation.get("message", ""),
                    violation.get("remediation_action", ""),
                    violation.get("remediation_owner", ""),
                    violation.get("field_affected", ""),
                    violation.get("current_value", "")
                ])

        csv_content = output.getvalue()
        output.close()

        return csv_content

    @staticmethod
    def generate_summary_text(analysis_result: Dict) -> str:
        """
        Generate text summary for clipboard.
        """
        filename = analysis_result.get("filename", "Unknown")
        total_deals = analysis_result.get("total_deals", 0)
        deals_with_issues = analysis_result.get("deals_with_issues", 0)
        health_score = analysis_result.get("health_score", 0)
        critical_issues = analysis_result.get("critical_issues", 0)
        warning_issues = analysis_result.get("warning_issues", 0)

        percentage = round((deals_with_issues / total_deals * 100), 1) if total_deals > 0 else 0

        summary = f"""RevTrust Pipeline Analysis Summary
{'='*50}

File: {filename}
Analyzed: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}

OVERALL HEALTH
- Total Deals: {total_deals}
- Deals with Issues: {deals_with_issues} ({percentage}%)
- Pipeline Health Score: {health_score}/100

ISSUES BREAKDOWN
- Critical Issues: {critical_issues}
- Warnings: {warning_issues}

TOP ISSUES BY CATEGORY
"""

        # Count issues by category
        violations_by_deal = analysis_result.get("violations_by_deal", {})
        category_counts = {}

        for violations in violations_by_deal.values():
            for violation in violations:
                category = violation.get("category", "Unknown")
                severity = violation.get("severity", "unknown")

                if category not in category_counts:
                    category_counts[category] = {"critical": 0, "warning": 0}

                if severity == "critical":
                    category_counts[category]["critical"] += 1
                elif severity == "warning":
                    category_counts[category]["warning"] += 1

        # Sort by total issues
        sorted_categories = sorted(
            category_counts.items(),
            key=lambda x: x[1]["critical"] + x[1]["warning"],
            reverse=True
        )

        for category, counts in sorted_categories[:5]:  # Top 5
            total = counts["critical"] + counts["warning"]
            summary += f"- {category}: {total} issues "
            summary += f"({counts['critical']} critical, {counts['warning']} warnings)\n"

        summary += f"\n{'='*50}\n"
        summary += "Generated by RevTrust - Pipeline Hygiene Analysis\n"

        return summary


def get_export_generator() -> ExportGenerator:
    """Get export generator instance"""
    return ExportGenerator()
